#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

BIN="/root/TCPSLAVE/TCP_Slave_Utility_project"
Monitscript="/usr/bin/monit -I"

start_service() {
    echo "Starting TCP Slave Utility..." >> /tmp/tcpslave.log
    enable=$(uci get tcpconfig.tcpconfig.enabletcp 2>/dev/null)
    if [ "$enable" != "1" ]; then
        echo "TCP Slave Utility is disabled or config not found." >> /tmp/tcpslave.log
        return
    fi

    procd_open_instance
    procd_set_param command $BIN
    procd_set_param respawn
    mv /Web_Page_Gateway_Apps/Common_GW_Files/monit.d/Monitor_TCP_Slave_Utility_project /etc/monit.d/
    procd_close_instance
    #/etc/monit start
    
      PSOutput=$(ps x)
     
    if echo "$PSOutput" | grep -q "$Monitscript"              
    then
		echo "monit daemon already running"
    else
        /etc/monit start
    fi
    
    
    
    sh /bin/modem.sh > /dev/null 2>&1 &
}

stop_service() {
    echo "Stopping TCP Slave Utility..." >> /tmp/tcpslave.log
    mv /etc/monit.d/Monitor_TCP_Slave_Utility_project /Web_Page_Gateway_Apps/Common_GW_Files/monit.d/
     /etc/monit stop
    /usr/bin/killall -9 monit
	/etc/monit start

    pid=$(pgrep -f "/root/TCPSLAVE/TCP_Slave_Utility_project")
    if [ -n "$pid" ]; then
        kill -TERM "$pid" > /dev/null 2>&1
    fi
}

start() {
    start_service
}

stop() {
    stop_service
}
