#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2015 OpenWrt.org

START=99
USE_PROCD=1

BIN="/bin/connectionDiagnostics"

start_service()
{
    running=$(uci get connectionDiagnostics.general.mode)
    enable=$(uci get connectionDiagnostics.general.enable)
    if [ $enable -eq 1 ] && [ "$running" = "start" ]
    then
        procd_open_instance
        procd_set_param command $BIN
        procd_close_instance
    fi
}

stop_service()
{
    pid=$(pgrep -f "/bin/connectionDiagnostics")
	kill -TERM "$pid" > /dev/null 2>&1
}
