#!/bin/sh /etc/rc.common

[ ! -x /usr/sbin/hwclock ] && exit 0

START=90
STOP=90
USE_PROCD=1

start_service() {
    #For snmp to get system information...
	/etc/snmp/systeminfo.sh
	/etc/init.d/snmpd restart
}

stop_service() {
    echo "Updated system related parameters..."

}
