#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

UpdateConfigScript="/root/InterfaceManager/script/features/mac_binding/UpdateMacConfig.sh"

case "$1" in
    list)
        echo '{"configure":{}}'
        ;;
    call)
        case "$2" in
                   configure)
                            response=$($UpdateConfigScript)
							if [ "$?" -ne 0 ]
                            then
								echo "{\"code\":1,\"output\":\"FAILURE :  Configuration Update\"}"
                            else
                               	echo "{\"code\":0,\"output\":\"SUCCESS : Configuration Update\"}"
                            fi
                                                                                 
                            ;;    
       
                    
                   #configure)         
							#response=$($UpdateConfigScript)
							#RetVal=$?
							#echo "{\"code\":\"0\",\"output\":\"Updated Configurations\"}"                                   
							 #;;
                    *)
                    echo '{"code":"1","output":"invalid method"}'
                    exit 1
                    ;;
        esac #appmanager method
            ;;
esac # ubus method

exit 0


