#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

macidconfig="/bin/macidblocking.sh"
case "$1" in
    list)
        echo '{"configure":{}}'
        ;;
    call)
        case "$2" in
                   configure)
                                                        response=$($macidconfig)
                                                        RetVal=$?
                                                        echo "{\"code\":\"0\",\"output\":\"Updated Configurations\"}"
                                                         ;;
                    *)
                    echo '{"code":"1","output":"invalid method"}'
                    exit 1
                    ;;
        esac #appmanager method
            ;;
esac # ubus method

exit 0
