#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

factoryresetscript="/root/InterfaceManager/script/Restore.sh"

case "$1" in
    list)
        echo '{"disable":{},"factoryreset":{}}'
        ;;
    call)
        case "$2" in
                    disable)
                             board_name=$(cat /tmp/sysinfo/board_name)
									echo 1 > /sys/class/gpio/gpio3/value
									pid=$(pgrep -f "/bin/Watchdog_Enable_Disable")
									kill -9 $pid
									Disablestatus=$(cat /sys/class/gpio/gpio3/value)                                                    
                            ;;                
                    *)
                    echo '{"code":"1","output":"invalid method"}'
                    exit 1
        esac #appmanager method
        ;;
esac # ubus method

exit 0
