#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

case "$1" in
    list)
        echo '{"configure":{}}'
        ;;
    call)
        case "$2" in
                                                                                                   
		             configure)
							    moduletype=$(uci get boardconfigfile.boardconfigfile.moduletype)
	                            uci set boardconfig.board.moduletype=${moduletype}
	                            uci commit boardconfig	                           
							    echo "{\"code\":1,\"output\":\"SUCCESS: Set Module Type\"}"
	                                                                                                         
                            ;;
                
		             *)
		                    echo '{"code":"1","output":"invalid method"}'
		                    exit 1
		                    ;;
     
        esac #appmanager method
        ;;
esac # ubus method

exit 0
