#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

UpdateConfigScript="/root/InterfaceManager/script/DMZ.sh"


case "$1" in
    list)
        echo '{"configure":{},"delete":{}}'
        ;;
    call)
        case "$2" in
                    configure)
                            response=$($UpdateConfigScript)
							if [ "$?" -ne 0 ]
                            then
								echo "{\"code\":1,\"output\":\"FAILURE : DMZ Configuration Update\"}"
                            else
                               	echo "{\"code\":0,\"output\":\"SUCCESS : DMZ Configuration Update\"}"
                            fi
                                                                                 
                            ;; 
                            
                                
                      #delete)
                            #response=$($DeleteConfigScript)
							#if [ "$?" -ne 0 ]
                            #then
								#echo "{\"code\":1,\"output\":\"FAILURE : DMZ Configuration Update\"}"
                            #else
                               	#echo "{\"code\":0,\"output\":\"SUCCESS : DMZ Configuration Update\"}"
                            #fi
                                                                                 
                            #;;                                                              
                    
		             *)
		                    echo '{"code":"1","output":"invalid method"}'
		                    exit 1
		                    ;;
     
        esac #appmanager method
        ;;
esac # ubus method

exit 0
