#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh


UpdateFirmwareScript="/bin/lteupdatefirmwarescript.sh"

case "$1" in
    list)
        echo '{"configure":{}}'
        ;;
    call)
        case "$2" in
                    configure)
                            response=$($UpdateFirmwareScript)
							if [ "$?" -ne 0 ]
                            then
								echo "{\"code\":1,\"output\":\"FAILURE : LTE Firmware Upgrade\"}"
                            else
                               	echo "{\"code\":0,\"output\":\"SUCCESS : LTE Firmware Upgrade\"}"
                            fi
                                                                                 
                            ;;                        
                                                                                        
		                           
		             *)
		                    echo '{"code":"1","output":"invalid method"}'
		                    exit 1
		                    ;;
     
        esac #appmanager method
        ;;
esac # ubus method

exit 0
