#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh
UpdateRouterAppConfigScript="/bin/UpdateConfigurationsRouterApp"

case "$1" in
    list)
        echo '{"configure":{}}'
        ;;
    call)
        case "$2" in
                    configure)
                            response=$($UpdateRouterAppConfigScript ucitoappcfg)
                            file="$(cat /bin/updatevpnconfigoutput.txt)" 
                         	echo "{\"code\":0,\"output\":\"\$response\"}"                                                                     
                            ;;                     
		                          
		             *)
		                    echo '{"code":"1","output":"invalid method"}'
		                    exit 1
		                    ;;
     
        esac #appmanager method
        ;;
esac # ubus method

exit 0
