#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

UpdateConfigScript="/bin/UpdateWanConfig.sh"
DeleteConfigScript="/root/InterfaceManager/script/Delete_Network_Interfaces.sh"

case "$1" in
    list)
        echo '{"configure":{"application":"ApplicationName","action":"ActionName"},"delete":{}}'
        ;;
    call)
        case "$2" in
                   configure)
		                # read the arguments
		                read -r input;
		                json_load "$input" > /dev/null 2>&1
		                json_get_var ApplicationName application
		                json_get_var ActionName action
	                    case "$ApplicationName" in
	                        "Update")
	                            case "$ActionName" in
	                                "updateinterface")
		                                    response=$($UpdateConfigScript)
		                                    RetVal=$?
		                                    echo "{\"code\":\"0\",\"output\":\"Configurations Updated\"}"                                   
		                                     ;;
	                                  *)
	                                    echo '{"code":"1","output":"invalid action"}'
	                                    exit 1
	                                    ;;
	                            esac #application action
	                            ;;
	                    esac #application name
	                    ;;
	                    
	                    
	                    delete)
                            response=$($DeleteConfigScript)
							if [ "$?" -ne 0 ]
                            then
								echo "{\"code\":1,\"output\":\"FAILURE :  Deleted\"}"
                            else
                               	echo "{\"code\":0,\"output\":\"SUCCESS : Deleted\"}"
                            fi
                                                                                 
                            ;;   
	                    
                    *)
                    echo '{"code":"1","output":"invalid method"}'
                    exit 1
        esac #appmanager method
            ;;
esac # ubus method

exit 0
