#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh


case "$1" in
    list)
          echo '{"configure":{}}'
        ;;
    call)
        case "$2" in
                    configure)
                          timeout=$(uci get webserverconfig.webserverconfig.sessiontimeout)
                         	echo "{\"code\":0,\"output\":\"$timeout\"}"                                                                                  
                            ;;
                            
                          # response1=$(SystemstartScript)
                           # echo "{\"code\":0,\"output\":\"$file\"}"
                                                      
                           
                    *)
                    echo '{"code":"1","output":"invalid method"}'
                    exit 1
        esac #appmanager method
        ;;
esac # ubus method

exit 0
