#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

UpdateConfigScript="/bin/QueryModemStatus.sh"
UpdateInterfaceScript="/bin/Check_Interface_Status.sh"

case "$1" in
    list)
        echo '{"configure":{},"check":{}}'
        ;;
    call)
        case "$2" in
                    configure)
                            file=$(cat /tmp/ModemAnalytics.txt) 
                         	echo "{\"code\":0,\"output\":\"$file\"}"                                                                        
                            ;;
                            
                          # response1=$(SystemstartScript)
                           # echo "{\"code\":0,\"output\":\"$file\"}"
                          
                    check)
                    
                            response=$($UpdateInterfaceScript)
                            resp=$(cat /tmp/InterfaceStatus.txt) 
                         	echo "{\"code\":0,\"output\":\"$resp\"}"                                                                        
                            ;;                                  
                           
                    *)
                    echo '{"code":"1","output":"invalid method"}'
                    exit 1
        esac #appmanager method
        ;;
esac # ubus method

exit 0
