#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

#UpdateAdminPasswordscript="/bin/UpdateAdminPassword.sh"

case "$1" in
    list)
        echo '{"configure":{}}'
        ;;
    call)
        case "$2" in
                    configure)
								pwd=$(uci get rpcdtemp.rpcdtemp.password)
								uci set rpcd.admin.password=$pwd
								uci commit rpcd
								#/etc/init.d/rpcd restart
								
                                if [ "$?" -ne 0 ]
	                            then
									echo "{\"code\":1,\"output\":\"Failure\"}"
	                            else
									echo "{\"code\":0,\"output\":\"Success\"}"
	                            fi                                          
                            ;;
                            
                          # response1=$(SystemstartScript)
                           # echo "{\"code\":0,\"output\":\"$file\"}"
                                                      
                           
                    *)
                    echo '{"code":"1","output":"invalid method"}'
                    exit 1
        esac #appmanager method
        ;;
esac # ubus method

exit 0
