#!/bin/sh
                                                                                                             
#common_execute_method_param "$parameter" "$permission" "$get_cmd" "$set_cmd" "xsd:$type" "$forcedinform"             
#  $forcedinform should be set to 1 if the parameter is included in the inform message otherwise empty                     
#  Default of $type = string                                                                                                                  
                                                                                                                 
#############################                                                                                         
#   Entry point functuons   #                                                                                              
#############################                                                                                                                      
prefix_list="$prefix_list $DMROOT.Credential."                                                                        
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_Credential"                                
entry_execute_method_list_forcedinform="$entry_execute_method_list_forcedinform  entry_execute_method_root_Credential"                        


###################
#connected
cp /dev/null data.json
ip neigh | grep -vwE "(fe80)" > /tmp/sort.txt
                                                                                                                                                                                                                                   
entry_execute_method_root_Credential() {                                                                                   
        case "$1" in ""|"$DMROOT."|"$DMROOT.Credential."*)                                                                                    
                common_execute_method_obj "$DMROOT.Credential." "1"                                              
                common_execute_method_param "$DMROOT.Credential.SSID" "1" "$UCI_GET remote.@update[0].ssid" "custom_set_ssid" "" "1"      
                common_execute_method_param "$DMROOT.Credential.passwd" "1" "$UCI_GET remote.@update[0].passwd" "custom_set_password" "" "1"
                common_execute_method_param "$DMROOT.Credential.RadioEnable" "1" "$UCI_GET remote.@update[0].radioenable" "custom_set_radioenable" "" "1"
		uci commit remote
			easycwmp_status=$(uci get remoteconfig.tr069.trenable)
		if [ "${easycwmp_status}" = "1" ];then
			/root/InterfaceManager/script/easycwmp_iface_parser.sh 
			/root/InterfaceManager/script/TR069.sh 
		fi
		i=0
		#while read -r line; do                                                       
  			#printf '%s\n' "$line"
			common_execute_method_param "$DMROOT.Credential.Interface" "0" "cat /tmp/out.txt" "" "" "1"
			common_execute_method_param "$DMROOT.Credential.connection" "0" "cat /tmp/sort.txt" "" "" "1"
			#i=$((i+1))
		#done 
		return 0;                                                                                
                ;;                                                                                               
        esac                                                                                                          
        return $E_INVALID_PARAMETER_NAME;                                                                                
}  

custom_set_ssid() {    
        local val="$1"                                    
        $UCI_SET remote.@update[0].ssid="$val"       
        return 0                                                                                     
}

custom_set_password(){
	local val="$1"
        $UCI_SET remote.@update[0].passwd="$val"
        return 0
}             

custom_set_radioenable(){
	local val="$1"
        $UCI_SET remote.@update[0].radioenable="$val"
        return 0
}   
