#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

factoryresetscript="/root/InterfaceManager/script/Restore.sh"
#ImportedBoardModel="/tmp/etc/config/system"
#ConfigBoardModel="/etc/config/system"
case "$1" in
    list)
        echo '{"rebootsys":{},"testarchive":{},"resetgateway":{}}'
        ;;
    call)
        case "$2" in
                                        
               rebootsys)
						    respreboot=$(/root/usrRPC/script/Board_Recycle_12V_Script.sh)
						    if [ "$?" -ne 0 ]
							then
								echo "{\"code\":1,\"output\":\"Reboot failure!!\"}"
							else
								echo "{\"code\":0,\"output\":\"Reboot Success!!\"}"
							fi
						    ;;
							    
		testarchive)     
				          
                #extracting tar file in tmp folder
                #RetMsg=$(tar -zxv -f "${ArchivedFileWithPath}" -C "${ArchiveDLPath}" 2>&1)
                 #config_load importexportgatewayconfig
                 #config_get enableretainboardconfig "importexportgatewayconfig" enableretainboardconfig
                 #enableretainboardconfig=$(uci get importexportgatewayconfig.importexportgatewayconfig.enableretainboardconfig)
		a=$(mkdir /tmp/etc 2>&1) 
		a=$(mkdir /tmp/etc/config 2>&1)

		/bin/import_utility
						
	            #ImportedBoardModelValue=$(grep -w "option model" ${ImportedBoardModel})
	            #ConfigBoardModelValue=$(grep -w "option model" ${ConfigBoardModel})
			#echo "retainconfig $enableretainboardconfig "
			#echo "$ImportedBoardModelValue $ConfigBoardModelValue" 
	            	            	
				#if [ "$enableretainboardconfig" = "1" ] && [ "$ImportedBoardModelValue" = "$ConfigBoardModelValue" ]
				#then
				
				
				cp -r /tmp/etc/config/ADCUtilityConfigGeneric /etc/config/
				cp -r /tmp/etc/config/analoginputconfig /etc/config/
				cp -r /tmp/etc/config/cloudconfig /etc/config/
				cp -r /tmp/etc/config/DiagnosticIOUtilities /etc/config/
			    cp -r /tmp/etc/config/digitalinputconfig /etc/config/
				cp -r /tmp/etc/config/RS232DeviceConfigGeneric /etc/config/
				cp -r /tmp/etc/config/RS232UtilityConfigGeneric /etc/config/
				#cp -r /tmp/etc/config/RS485DeviceConfigGeneric /etc/config/
				cp -r /tmp/etc/config/Jsonconfig /etc/config/
				cp -r /tmp/etc/config/registerconfig /etc/config/
				cp -r /tmp/etc/config/blockconfig /etc/config/
				cp -r /tmp/etc/config/alarmconfig /etc/config/
				cp -r /tmp/etc/config/DeviceConfigGeneric /etc/config/
		        cp -r /tmp/etc/config/RS485UtilityConfigGeneric /etc/config/
				cp -r /tmp/etc/config/temperatureconfig /etc/config/
				cp -r /tmp/etc/config/sourceconfig /etc/config/
				cp -r /tmp/etc/config/portconfig /etc/config/
				cp -r /tmp/etc/config/applicationoverviewconfig /etc/config/
				cp -r /tmp/etc/config/PseudoCloudconfig /etc/config/
				cp -r /tmp/etc/config/PseudoRegisterconfig /etc/config/
				cp -r /tmp/etc/config/cloudconfigGeneric /etc/config/
				cp -r /tmp/etc/config/pseudoParamconfig /etc/config/
				cp -r /tmp/etc/config/tcpconfig /etc/config/
			    #cp -r /tmp/etc/config/system /etc/config/	
				#cp -r /tmp/etc/config/importexportgatewayconfig /etc/config/
				
				/bin/UpdateConfigurationsGateway rs485utilitycfg
				/bin/UpdateConfigurationsGateway UpdateRS232UtilityCfg
				/bin/UpdateConfigurationsGateway UpdateADCUtilityCfg
				#rm -f /tmp/backup.txt
				#cp -r /tmp/etc/* /etc
				
				
			#sleep 1
			
			#elif [ "$ImportedBoardModelValue" != "$ConfigBoardModelValue"  ]
				#then
				    #echo "{\"code\":1,\"output\":\"Invalid Import archieve\"}"
				#fi			   
                ;;			    
				
                    
                    
                    
          resetgateway)
          
							  
					sh -x /etc/init.d/GD44AppManager stop

					uci set applist_config.appconfig.running="0"
					uci commit applist_config

					rm /etc/ser2net.conf

					cp -r /Web_Page_Gateway_Apps/Default_Gateway/config /etc/
					cp /Web_Page_Gateway_Apps/Default_Gateway/ser2net.conf /etc/


					/root/usrRPC/script/Board_Recycle_12V_Script.sh

          
          
                sleep 1    
 
			      
        esac #appmanager method
        ;;
        *)
								echo '{"code":"1","output":"invalid method"}'
                    exit 1
                    
esac # ubus method

exit 0
